using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Microsoft.Data.Sqlite;

namespace Elektronische_Wandernadel
{
    /// <summary>
    /// Interaktionslogik für Window2.xaml
    /// </summary>
    public partial class Window2 : Window
    {
        Database database = new Database();

        private string connectionString = "Data Source=HWN_Datenbank.db";
        public Window2()
        {
            InitializeComponent();
            DatenAnzeigen();
        }

        public void tabellezurückButton_Click(object sender, RoutedEventArgs e)
        {
            MainWindow window = new MainWindow();
            window.Show();
            this.Close();
        }

        internal void HWNDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            HWNDataGrid.Columns[0].Visibility = Visibility.Collapsed;
        }

        internal void DatenAnzeigen()
        {
                using SqliteConnection connection = database.DatenbankVerbinden();

                string sql = "SELECT id, HWNNr, Name, Erreicht, Stempel FROM Wandernadel";

                using SqliteCommand command = new SqliteCommand(sql, connection);
                using SqliteDataReader reader = command.ExecuteReader();

                DataTable tabelle = new DataTable();
                tabelle.Load(reader);

                HWNDataGrid.ItemsSource = tabelle.DefaultView;

        }

        internal void löschenButton_Click( object sender, RoutedEventArgs e )
        {
           MessageBoxResult result = MessageBox.Show("Möchtest du das wirklich machen? ALLE Daten werden unwiderruflich gelöscht!", "Warnung", MessageBoxButton.YesNo, MessageBoxImage.Warning);

            if (result == MessageBoxResult.Yes)
            {
                Database database = new Database();
                database.DeleteTabelle();
                HWNDataGrid.ItemsSource = null;
            }

            else
            {

            }
        }

        internal void ändernButton_Click(Object sender, RoutedEventArgs e)
        {
            if (HWNDataGrid.ItemsSource != null)
            {
                try
                {
                    using SqliteConnection connection = database.DatenbankVerbinden();

                    foreach (DataRowView rowView in HWNDataGrid.ItemsSource)
                    {
                        DataRow row = rowView.Row;

                        string sql = @"
                            UPDATE Wandernadel
                            SET HWNNr = $hwnnr,
                            Name = $name,
                            Erreicht = $erreicht,
                            Stempel = $stempel
                            WHERE Id = $id;";

                        using SqliteCommand command = new SqliteCommand(sql, connection);

                        command.Parameters.AddWithValue("$id", row["Id"]);
                        command.Parameters.AddWithValue("$hwnnr", row["HWNNr"]);
                        command.Parameters.AddWithValue("$name", row["Name"]);
                        command.Parameters.AddWithValue("$erreicht", row["erreicht"]);
                        command.Parameters.AddWithValue("$stempel", row["Stempel"]);

                        command.ExecuteNonQuery();


                    }

                    MessageBox.Show("Änderungen wurden gespeichert!","Erfolg");
                }

                catch
                {
                    MessageBox.Show("Die HWN- und Stempelnummern müssen weiterhin Nummern sein.", "Ungültige Eingabe");
                }
            }

            else
            {
                MessageBox.Show("Du hast deine Tabelle gerade gelöscht. Bitte gehe zurück in den Startbildschirm, damit eine neue erstellt werden kann.","Fehler");
            }

        }
        
    }
}
